package ufop.smd.modelo;

// Generated 10/01/2012 17:36:01 by Hibernate Tools 3.2.1.GA

import java.sql.Time;
import java.util.Date;

import ufop.smd.controle.utils.Criptografia;
import ufop.smd.controle.utils.Datas;
import ufop.smd.controle.utils.Horas;
import android.content.ContentValues;
import android.database.Cursor;
import android.util.Log;

/**
 * Agente generated by hbm2java
 */
public class Agente implements java.io.Serializable {

	private Integer idAgente;
	private Integer codigo;
	private String nome;
	private boolean ativo;
	private String login;
	private String senha;
	private Date dataNascimento;
	private String telefone;
	private Date dataCadastro;
	private Time horaCadastro;
	private Integer numeroAmostra;
	private Integer anoAmostra;

	public Agente() {
	}

	public Agente(Integer codigo, String nome, boolean ativo, String login,
			String senha, Date dataCadastro, Time horaCadastro,
			Integer numeroAmostra, Integer anoAmostra) {
		this.codigo = codigo;
		this.nome = nome;
		this.ativo = ativo;
		this.login = login;
		this.setSenhaComMD5(senha);
		this.dataCadastro = dataCadastro;
		this.horaCadastro = horaCadastro;
		this.numeroAmostra = numeroAmostra;
		this.anoAmostra = anoAmostra;
	}

	public Agente(Integer codigo, String nome, boolean ativo, String login,
			String senha, Date dataNascimento, String telefone,
			Date dataCadastro, Time horaCadastro, Integer numeroAmostra, Integer anoAmostra) {
		this(codigo, nome, ativo, login, senha, dataCadastro, horaCadastro,
				numeroAmostra, anoAmostra);
		this.telefone = telefone;
		this.dataNascimento = dataNascimento;
	}

	public Agente(Cursor cursor) {

		this.setIdAgente(cursor.getInt(0));
		this.setCodigo(cursor.getInt(1));
		this.setNome(cursor.getString(2));
		this.setAtivo((cursor.getInt(3) == 1 ? true : false));
		this.setLogin(cursor.getString(4));
		this.setSenha(cursor.getString(5));
		this.setDataNascimento(Datas.getDate(cursor.getString(6)));
		this.setTelefone(cursor.getString(7));
		this.setDataCadastro(Datas.getDate(cursor.getString(8)));
		this.setHoraCadastro(Horas.getTime(cursor.getString(9)));
		this.setNumeroAmostra(cursor.getInt(10));
		this.setAnoAmostra(cursor.getInt(11));

	}

	public ContentValues getContentValues() {

		ContentValues values = new ContentValues();

		values.put("idAgente", this.getIdAgente() != null ? this.getIdAgente()
				: null);
		values.put("codigo", this.getCodigo());
		values.put("nome", this.getNome());
		values.put("ativo", this.isAtivo());
		values.put("login", this.getLogin());
		values.put("senha", this.getSenha());
		values.put("dataNascimento",
				this.getDataNascimento() != null ? Datas.getText(
						this.getDataNascimento(), "yyyy-MM-dd") : null);
		values.put("telefone", this.getTelefone());
		values.put("dataCadastro",
				this.getDataCadastro() != null ? Datas.getText(
						this.getDataCadastro(), "yyyy-MM-dd") : null);
		values.put("horaCadastro", this.getHoraCadastro() != null ? this
				.getHoraCadastro().toString() : null);
		values.put("numeroAmostra", this.getNumeroAmostra());
		values.put("anoAmostra", this.getAnoAmostra());

		return values;
	}

	public Integer getIdAgente() {
		return this.idAgente;
	}

	public void setIdAgente(Integer idAgente) {
		this.idAgente = idAgente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public boolean isAtivo() {
		return this.ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public void setSenhaComMD5(String senha) {
		this.senha = Criptografia.md5(senha);
	}

	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public Time getHoraCadastro() {
		return this.horaCadastro;
	}

	public void setHoraCadastro(Time horaCadastro) {
		this.horaCadastro = horaCadastro;
	}

	public Integer getCodigo() {
		return codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Integer getNumeroAmostra() {
		return numeroAmostra;
	}

	public void setNumeroAmostra(Integer numeroAmostra) {
		if(numeroAmostra != null){
			this.numeroAmostra = numeroAmostra;
		} else {
			numeroAmostra = 0;
		}
	}

	public Integer getAnoAmostra() {
		return anoAmostra;
	}

	public void setAnoAmostra(Integer anoAmostra) {
		if(anoAmostra != null){
			this.anoAmostra = anoAmostra;
		} else {
			anoAmostra = 0;
		}
	}
	
	
}
