package ufop.smd.modelo;
// Generated 10/01/2012 17:36:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import ufop.smd.controle.utils.Datas;
import android.content.ContentValues;
import android.database.Cursor;
import android.os.Parcel;
import android.os.Parcelable;

/**
 * Boletimtratamento generated by hbm2java
 */
public class Boletimtratamento  implements Parcelable {


	private Integer idBoletimTratamento;
	private Integer idAgente;
	private Integer idLocalidade;
	private Integer idMunicipio;
	private String coordenadorRegional;
	private String grs;
	private String categoria;
	private String turma;
	private Date data;
	private String semanaEpid;
	private String numeroAtividade;
	private String tipoAtividade;
	private Date sincronizadoEm;
	private boolean ativo;

	public Boletimtratamento() {
	}


	public Boletimtratamento(Integer agente, Integer localidade, Integer municipio, String coordenadorRegional, String grs, String categoria, 
			String turma, Date data, String semanaEpid, String numeroAtividade, String tratamentoAtividade, boolean ativo) {
		this.idAgente = agente;
		this.idLocalidade = localidade;
		this.idMunicipio = municipio;
		this.coordenadorRegional = coordenadorRegional;
		this.grs = grs;
		this.categoria = categoria;
		this.turma = turma;
		this.data = data;
		this.semanaEpid = semanaEpid;
		this.numeroAtividade = numeroAtividade;
		this.tipoAtividade = tratamentoAtividade;
		this.ativo = ativo;
	}

	public Boletimtratamento(Cursor cursor){

		this.setIdBoletimTratamento(cursor.getInt(0));
		this.setCoordenadorRegional(cursor.getString(1));
		this.setGrs(cursor.getString(2));
		this.setIdMunicipio(cursor.getInt(3));
		this.setIdLocalidade(cursor.getInt(4));
		this.setCategoria(cursor.getString(5));
		this.setIdAgente(cursor.getInt(6));
		this.setTurma(cursor.getString(7));
		this.setData(Datas.getDate(cursor.getString(8)));
		this.setSemanaEpid(cursor.getString(9));
		this.setNumeroAtividade(cursor.getString(10));
		this.setTipoAtividade(cursor.getString(11));
		this.setSincronizadoEm(Datas.getDate(cursor.getString(12)));
		this.setAtivo((cursor.getInt(13) == 1 ? true : false));

	}

	public void writeToParcel(Parcel dest, int flags) {

		dest.writeInt(getIdBoletimTratamento());
		dest.writeString(getCoordenadorRegional());
		dest.writeString(getGrs());
		dest.writeInt(getIdMunicipio());
		dest.writeInt(getIdLocalidade());
		dest.writeString(getCategoria());
		dest.writeInt(getIdAgente());
		dest.writeString(getTurma());
		dest.writeString(Datas.getText(getData(), "yyyy-MM-dd"));
		dest.writeString(getSemanaEpid());
		dest.writeString(getNumeroAtividade());
		dest.writeString(getTipoAtividade().toString());
		dest.writeString(Datas.getText(getSincronizadoEm(), "yyyy-MM-dd"));
		dest.writeString(isAtivo() + "");

	}

	public static final Parcelable.Creator<Boletimtratamento> CREATOR = new Parcelable.Creator<Boletimtratamento>() {


		public Boletimtratamento createFromParcel(Parcel parcel) {

			Boletimtratamento bol = new Boletimtratamento();

			bol.setIdBoletimTratamento(parcel.readInt());
			bol.setCoordenadorRegional(parcel.readString());
			bol.setGrs(parcel.readString());
			bol.setIdMunicipio(parcel.readInt());
			bol.setIdLocalidade(parcel.readInt());
			bol.setCategoria(parcel.readString());
			bol.setIdAgente(parcel.readInt());
			bol.setTurma(parcel.readString());
			String data = parcel.readString();
			bol.setData(Datas.getDate(data));
			bol.setSemanaEpid(parcel.readString());
			bol.setNumeroAtividade(parcel.readString());
			bol.setTipoAtividade(parcel.readString());
			bol.setSincronizadoEm(Datas.getDate(parcel.readString()));
			bol.setAtivo(new Boolean(parcel.readString()));

			return bol;
		}


		public Boletimtratamento[] newArray(int numElementos) {
			return new Boletimtratamento[numElementos];
		}
	};

	public ContentValues getContentValues(){

		ContentValues values = new ContentValues();

		values.put("idBoletimTratamento", this.getIdBoletimTratamento() != null ? this.getIdBoletimTratamento() : null);
		values.put("idAgente", this.getIdAgente());
		values.put("idLocalidade", this.getIdLocalidade());
		values.put("idMunicipio", this.getIdMunicipio());
		values.put("coordenadorRegional", this.getCoordenadorRegional() != null ? this.getCoordenadorRegional() : null);
		values.put("grs", this.getGrs());
		values.put("categoria", this.getCategoria());
		values.put("turma", this.getTurma());
		values.put("data", this.getData() != null ? Datas.getText(this.getData(), "yyyy-MM-dd") : null);
		values.put("semanaEpid", this.getSemanaEpid() != null ? this.getSemanaEpid() : null);
		values.put("numeroAtividade", this.getNumeroAtividade() != null ? this.getNumeroAtividade() : null);
		values.put("tipoAtividade", this.getTipoAtividade() != null ? this.getTipoAtividade() : null);
		values.put("ativo", this.isAtivo());

		return values;
	}

	public int describeContents() {
		return 0;
	}

	public Integer getIdBoletimTratamento() {
		return this.idBoletimTratamento;
	}

	public void setIdBoletimTratamento(Integer idBoletimTratamento) {
		this.idBoletimTratamento = idBoletimTratamento;
	}
	public Integer getIdAgente() {
		return this.idAgente;
	}

	public void setIdAgente(Integer agente) {
		this.idAgente = agente;
	}
	public Integer getIdLocalidade() {
		return this.idLocalidade;
	}

	public void setIdLocalidade(Integer localidade) {
		this.idLocalidade = localidade;
	}
	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer municipio) {
		this.idMunicipio = municipio;
	}
	public String getCoordenadorRegional() {
		return this.coordenadorRegional;
	}

	public void setCoordenadorRegional(String coordenadorRegional) {
		this.coordenadorRegional = coordenadorRegional;
	}
	public String getGrs() {
		return this.grs;
	}

	public void setGrs(String grs) {
		this.grs = grs;
	}
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	public String getTurma() {
		return this.turma;
	}

	public void setTurma(String turma) {
		this.turma = turma;
	}
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}
	public String getSemanaEpid() {
		return this.semanaEpid;
	}

	public void setSemanaEpid(String semanaEpid) {
		this.semanaEpid = semanaEpid;
	}
	public String getNumeroAtividade() {
		return this.numeroAtividade;
	}

	public void setNumeroAtividade(String numeroAtividade) {
		this.numeroAtividade = numeroAtividade;
	}
	public String getTratamentoAtividade() {
		return this.getTipoAtividade();
	}

	public void setTratamentoAtividade(String tratamentoAtividade) {
		this.setTipoAtividade(tratamentoAtividade);
	}
	public Date getSincronizadoEm() {
		return this.sincronizadoEm;
	}

	public void setSincronizadoEm(Date sincronizadoEm) {
		this.sincronizadoEm = sincronizadoEm;
	}

	public String getTipoAtividade() {
		return tipoAtividade;
	}

	public void setTipoAtividade(String tipoAtividade) {
		this.tipoAtividade = tipoAtividade;
	}

	public boolean isAtivo() {
		return ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}







}


