package ufop.smd.modelo;
// Generated 10/01/2012 17:36:01 by Hibernate Tools 3.2.1.GA


import android.content.ContentValues;
import android.database.Cursor;

/**
 * Imovel generated by hbm2java
 */
public class Imovel  implements java.io.Serializable {


	private Integer idImovel;
	private Integer idQuadra;
	private Integer idLogradouro;
	private String numero;
	private String complemento;

	public Imovel() {
	}
	public Imovel(Integer quadra, Integer logradouro, String numero, String complemento) {
		this.idQuadra = quadra;
		this.idLogradouro = logradouro;
		this.numero = numero;
		this.complemento = complemento;
	}
	public Imovel(Integer quadra, Integer logradouro, String numero) {
		this.idQuadra = quadra;
		this.idLogradouro = logradouro;
		this.numero = numero;
	}
	public Imovel(Cursor cursor){
		setIdImovel(cursor.getInt(0));
		setIdQuadra(cursor.getInt(1));
		setIdLogradouro(cursor.getInt(2));
		setNumero(cursor.getString(3));
		setComplemento(cursor.getString(4));
	}

	public ContentValues getContentValues(){

		ContentValues values = new ContentValues();

		values.put("idImovel", this.getIdImovel() != null ? this.getIdImovel() : null);
		values.put("idQuadra", this.getIdQuadra());
		values.put("idLogradouro", this.getIdLogradouro());
		values.put("numero", this.getNumero());
		values.put("complemento", this.getComplemento());

		return values;
	}

	public Integer getIdImovel() {
		return idImovel;
	}

	public void setIdImovel(Integer idImovel) {
		this.idImovel = idImovel;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public Integer getIdQuadra() {
		return idQuadra;
	}

	public void setIdQuadra(Integer quadra) {
		this.idQuadra = quadra;
	}

	public Integer getIdLogradouro() {
		return idLogradouro;
	}

	public void setIdLogradouro(Integer logradouro) {
		this.idLogradouro = logradouro;
	}


}


