package ufop.smd.modelo;
// Generated 10/01/2012 17:36:01 by Hibernate Tools 3.2.1.GA


import java.sql.Time;
import java.util.Date;

import ufop.smd.controle.utils.Datas;
import ufop.smd.controle.utils.Horas;
import android.content.ContentValues;
import android.database.Cursor;

/**
 * Localidade generated by hbm2java
 */
public class Localidade  implements java.io.Serializable {

	private Integer idLocalidade;
	private Integer idMunicipio;
	private Integer codigo;
	private String nome;
	private boolean croqui;
	private Date dataCroqui;
	private Time horaCroqui;

	public Localidade() {
	}
	public Localidade(Integer municipio, Integer codigo, String nome, boolean croqui, Date dataCroqui, Time horaCroqui){
		this.idMunicipio = municipio;
		this.codigo = codigo;
		this.nome = nome;
		this.croqui = croqui;
		this.dataCroqui = dataCroqui;
		this.horaCroqui = horaCroqui;
	}
	public Localidade(Integer idLocalidade, Integer municipio, Integer codigo, String nome, boolean croqui, Date dataCroqui, Time horaCroqui) {
		this.idLocalidade = idLocalidade;
		this.idMunicipio = municipio;
		this.codigo = codigo;
		this.nome = nome;
		this.croqui = croqui;
		this.dataCroqui = dataCroqui;
		this.horaCroqui = horaCroqui;
	}
	public Localidade(Cursor cursor){

		if(cursor != null ){
			this.setIdLocalidade(cursor.getInt(0));
			this.setIdMunicipio(cursor.getInt(1));
			this.setCodigo(cursor.getInt(2));
			this.setNome(cursor.getString(3));
			this.setCroqui((cursor.getInt(4) == 1 ? true : false));
			this.setDataCroqui(Datas.getDate(cursor.getString(5)));
			this.setHoraCroqui(Horas.getTime(cursor.getString(6)));
		}

	}

	public ContentValues getContentValues(){

		ContentValues values = new ContentValues();

		values.put("idLocalidade", this.getIdLocalidade() != null ? this.getIdLocalidade() : null);
		values.put("idMunicipio", this.getIdMunicipio());
		values.put("codigo", this.getCodigo());
		values.put("nome", this.getNome());
		values.put("croqui", this.isCroqui());
		values.put("dataCroqui", this.getDataCroqui() != null ? Datas.getText(this.getDataCroqui(), "yyyy-MM-dd") : null);
		values.put("horaCroqui", this.getHoraCroqui() != null ? this.getHoraCroqui().toString() : null);

		return values;
	}

	public Integer getIdLocalidade() {
		return this.idLocalidade;
	}

	public void setIdLocalidade(Integer idLocalidade) {
		this.idLocalidade = idLocalidade;
	}
	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer municipio) {
		this.idMunicipio = municipio;
	}
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public boolean isCroqui() {
		return croqui;
	}

	public void setCroqui(boolean croqui) {
		this.croqui = croqui;
	}

	public Date getDataCroqui(){
		return this.dataCroqui;
	}

	public void setDataCroqui(Date dataCroqui){
		this.dataCroqui = dataCroqui;
	}

	public Time getHoraCroqui(){
		return this.horaCroqui;
	}

	public void setHoraCroqui(Time horaCroqui){
		this.horaCroqui = horaCroqui;
	}

	public String toStringCroqui(){
		return (this.croqui ? "Sim" : "Não");
	}

	public Integer getCodigo() {
		return codigo;
	}

	public void setCodigo(Integer codigo){
		this.codigo = codigo;
	}
}


