package ufop.smd.modelo;
// Generated 10/01/2012 17:36:01 by Hibernate Tools 3.2.1.GA


import android.content.ContentValues;
import android.database.Cursor;
import android.util.Log;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private String codigo;
     private String nome;
     private String estado;

    public Municipio() {
    }
    public Municipio(Integer idMunicipio, String codigo, String nome, String estado){
        this.idMunicipio = idMunicipio;
        this.codigo = codigo;
        this.nome = nome;
        this.estado = estado;
    }
    public Municipio(String codigo, String nome, String estado) {
        this.codigo = codigo;
        this.nome = nome;
        this.estado = estado;
    }
    public Municipio(Cursor cursor){

    	this.setIdMunicipio(cursor.getInt(0));
    	this.setCodigo(cursor.getString(1));
    	this.setNome(cursor.getString(2));
    	this.setEstado(cursor.getString(3));
    	
    }
    
    public ContentValues getContentValues(){
    	
    	ContentValues values = new ContentValues();
    	
    	values.put("idMunicipio", this.getIdMunicipio() != null ? this.getIdMunicipio() : null);
    	values.put("codigo", this.getCodigo());
		values.put("nome", this.getNome());
		values.put("estado", this.getEstado());
				
		return values;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public String getCodigo(){
        return this.codigo;
    }
    public void setCodigo(String codigo){
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

}


