package ufop.smd.modelo;

import android.content.ContentValues;

/**
 * Quadralogradouro generated by hbm2java
 */
public class Quadralogradouro implements java.io.Serializable {

    private Integer idQuadraLogradouro;
    private Integer idQuadra;
    private Integer idLogradouro;

    public Quadralogradouro() {
    }

    public Quadralogradouro(Integer quadra, Integer logradouro) {
        this.idQuadra = quadra;
        this.idLogradouro = logradouro;
    }
    
	public ContentValues getContentValues(){

		ContentValues values = new ContentValues();
		values.put("idQuadraLogradouro", this.getIdQuadraLogradouro());
		values.put("idQuadra", this.getIdQuadra() != null ? this.getIdQuadra() : null);
		values.put("idLogradouro", this.getIdLogradouro() != null ? this.getIdLogradouro() : null);
		
		return values;
	}

    public Integer getIdQuadraLogradouro() {
        return this.idQuadraLogradouro;
    }

    public void setIdQuadraLogradouro(Integer idQuadraLogradouro) {
        this.idQuadraLogradouro = idQuadraLogradouro;
    }

    public Integer getIdQuadra() {
        return this.idQuadra;
    }

    public void setIdQuadra(Integer quadra) {
        this.idQuadra = quadra;
    }

    public Integer getIdLogradouro() {
        return this.idLogradouro;
    }

    public void setIdLogradouro(Integer logradouro) {
        this.idLogradouro = logradouro;
    }

    @Override
    public boolean equals(Object obj) {

        Quadralogradouro outra = (Quadralogradouro) obj;

        if (this.idQuadraLogradouro == outra.idQuadraLogradouro) {
            return true;
        }
        
        if(this.idQuadra.equals(outra.getIdQuadra()) 
                && this.getIdLogradouro().equals(outra.getIdLogradouro())){
            return true;
            
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.idQuadraLogradouro != null ? this.idQuadraLogradouro : 0);
        hash = 97 * hash + (this.idQuadra != null ? this.getIdQuadra() : 0);
        hash = 97 * hash + (this.idLogradouro != null ? this.getIdLogradouro() : 0);
        return hash;
    }
}
