package ufop.smd.modelo;

import java.sql.Time;

import ufop.smd.controle.utils.Horas;
import android.content.ContentValues;
import android.database.Cursor;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

/**
 * Visitapesquisa generated by hbm2java
 */
public class Visitapesquisa implements Parcelable {

    private Integer idVisitaPesquisa;
    private Integer idBoletimpesquisa;
    private Integer idQuadra;
    private Integer idLogradouro;
    private Integer idImovel;
    private String tipoUnidade;
    private Integer numeroTubitos;
    private Integer numeroAmostra;
    private Integer larvasAeg;
    private Integer larvasAlb;
    private Integer larvasOut;
    private boolean examinadoLaboratorio;
    private Integer depositosInspecionados;
    private boolean ultimaVisitaBoletim;
    private boolean quadraConcluida;
    private Time hora;

    public Visitapesquisa() {
    }

    public Visitapesquisa(Integer idBoletim, Integer idQuadra, Integer idLogradouro, Integer idImovel, String tipoUnidade, boolean examinadoLaboratorio, 
    		int depositosInspecionados, boolean ultimaVisitaBoletim, boolean quadraConcluida, Time hora) {
        this.idBoletimpesquisa = idBoletim;
    	this.idQuadra = idQuadra;
        this.idLogradouro = idLogradouro;
        this.idImovel = idImovel;
        this.tipoUnidade = tipoUnidade;
        this.examinadoLaboratorio = examinadoLaboratorio;
        this.depositosInspecionados = depositosInspecionados;
        this.ultimaVisitaBoletim = ultimaVisitaBoletim;
        this.quadraConcluida = quadraConcluida;
        this.hora = hora;
    }

    public Visitapesquisa(Integer idBoletim, Integer idQuadra, Integer idLogradouro, Integer idImovel, String tipoUnidade, Integer numeroTubitos, 
    		Integer numeroAmostra, Integer larvasAeg, Integer larvasAlb, Integer larvasOut, boolean examinadoLaboratorio, 
    		int depositosInspecionados, boolean ultimaVisitaBoletim, boolean quadraConcluida, Time hora) {
    	this.idBoletimpesquisa = idBoletim;
    	this.idQuadra = idQuadra;
        this.idLogradouro = idLogradouro;
        this.idImovel = idImovel;
        this.tipoUnidade = tipoUnidade;
        this.numeroTubitos = numeroTubitos;
        this.numeroAmostra = numeroAmostra;
        this.larvasAeg = larvasAeg;
        this.larvasAlb = larvasAlb;
        this.larvasOut = larvasOut;
        this.examinadoLaboratorio = examinadoLaboratorio;
        this.depositosInspecionados = depositosInspecionados;
        this.ultimaVisitaBoletim = ultimaVisitaBoletim;
        this.quadraConcluida = quadraConcluida;
        this.hora = hora;
    }
    public Visitapesquisa(Cursor cursor){

		setIdVisitaPesquisa(cursor.getInt(0));
		setIdBoletimpesquisa(cursor.getInt(1));
		setIdQuadra(cursor.getInt(2));
		setIdLogradouro(cursor.getInt(3));
		setIdImovel(cursor.getInt(4));
		setTipoUnidade(cursor.getString(5));
		setNumeroTubitos(cursor.getInt(6));
		setNumeroAmostra(cursor.getInt(7));
		setLarvasAeg(cursor.getInt(8));
		setLarvasAlb(cursor.getInt(9));
		setLarvasOut(cursor.getInt(10));
		setExaminadoLaboratorio((cursor.getInt(11) == 1 ? true : false));
		setDepositosInspecionados(cursor.getInt(12));
		setUltimaVisitaBoletim((cursor.getInt(13) == 1 ? true : false));
		setQuadraConcluida((cursor.getInt(14) == 1 ? true : false));
		setHora(Horas.getTime(cursor.getString(15)));

	}
    
    public int describeContents() {
		return 0;
	}

	public void writeToParcel(Parcel dest, int flags) {

		dest.writeInt(idVisitaPesquisa);
		dest.writeInt(idBoletimpesquisa);
		dest.writeInt(idQuadra);
		dest.writeInt(idLogradouro);
		dest.writeInt(idImovel);
		dest.writeString(tipoUnidade);
		dest.writeInt(numeroTubitos);
		dest.writeInt(numeroAmostra);
		dest.writeInt(larvasAeg);
		dest.writeInt(larvasAlb);
		dest.writeInt(larvasOut);
		dest.writeString(examinadoLaboratorio + "");
		dest.writeInt(depositosInspecionados);
		dest.writeString(ultimaVisitaBoletim + "");
		dest.writeString(quadraConcluida + "");
		dest.writeString(hora + "");

	}

	public static final Parcelable.Creator<Visitapesquisa> CREATOR = new Parcelable.Creator<Visitapesquisa>() {


		public Visitapesquisa createFromParcel(Parcel parcel) {

			Visitapesquisa vis = new Visitapesquisa();

			vis.setIdVisitaPesquisa(parcel.readInt());
			vis.setIdBoletimpesquisa(parcel.readInt());
			vis.setIdQuadra(parcel.readInt());
			vis.setIdLogradouro(parcel.readInt());
			vis.setIdImovel(parcel.readInt());
			vis.setTipoUnidade(parcel.readString());
			vis.setNumeroTubitos(parcel.readInt());
			vis.setNumeroAmostra(parcel.readInt());
			vis.setLarvasAeg(parcel.readInt());
			vis.setLarvasAlb(parcel.readInt());
			vis.setLarvasOut(parcel.readInt());
			vis.setExaminadoLaboratorio(new Boolean(parcel.readString()));
			vis.setDepositosInspecionados(parcel.readInt());
			vis.setUltimaVisitaBoletim(new Boolean(parcel.readString()));
			vis.setQuadraConcluida(new Boolean(parcel.readString()));
			vis.setHora(Horas.getTime(parcel.readString()));

			return vis;
		}


		public Visitapesquisa[] newArray(int numElementos) {
			return new Visitapesquisa[numElementos];
		}
	};
    
    public ContentValues getContentValues(){

		ContentValues values = new ContentValues();
		
		values.put("idVisitaPesquisa", this.getIdVisitaPesquisa() != null ? this.getIdVisitaPesquisa() : null);
		values.put("idBoletimPesquisa", this.getIdBoletimpesquisa() != null ? this.getIdBoletimpesquisa() : null);
		values.put("idQuadra", this.getIdQuadra() != null ? this.getIdQuadra() : null);
		values.put("idLogradouro", this.getIdLogradouro() != null ? this.getIdLogradouro() : null);
		values.put("idImovel", this.getIdImovel() != null ? this.getIdImovel() : null);
		values.put("tipoUnidade", this.getTipoUnidade() != null ? this.getTipoUnidade() : null);
		values.put("numeroTubitos", this.getNumeroTubitos() != null ? this.getNumeroTubitos() : null);
		values.put("numeroAmostra", this.getNumeroAmostra() != null ? this.getNumeroAmostra() : null);
		values.put("larvasAeg", this.getLarvasAeg() != null ? this.getLarvasAeg() : null);
		values.put("larvasAlb", this.getLarvasAlb() != null ? this.getLarvasAlb() : null);
		values.put("larvasOut", this.getLarvasOut() != null ? this.getLarvasOut() : null);
		values.put("examinadoLaboratorio", this.isExaminadoLaboratorio());
		values.put("depositosInspecionados", this.getDepositosInspecionados());
		values.put("ultimaVisitaBoletim", this.isUltimaVisitaBoletim());
		values.put("quadraConcluida", this.isQuadraConcluida());
		values.put("hora", this.getHora() != null ? this.getHora().toString() : null);
		
		return values;
	}

    public Integer getIdVisitaPesquisa() {
        return this.idVisitaPesquisa;
    }

    public void setIdVisitaPesquisa(Integer idVisitaPesquisa) {
        this.idVisitaPesquisa = idVisitaPesquisa;
    }

    public Integer getIdQuadra() {
        return this.idQuadra;
    }

    public void setIdQuadra(Integer quadra) {
        this.idQuadra = quadra;
    }

    public Integer getIdLogradouro() {
        return this.idLogradouro;
    }

    public void setIdLogradouro(Integer logradouro) {
        this.idLogradouro = logradouro;
    }

    public Integer getIdImovel() {
        return this.idImovel;
    }

    public void setIdImovel(Integer imovel) {
        this.idImovel = imovel;
    }

    public String getTipoUnidade() {
        return this.tipoUnidade;
    }

    public void setTipoUnidade(String tipoUnidade) {
        this.tipoUnidade = tipoUnidade;
    }

    public Integer getNumeroTubitos() {
        return this.numeroTubitos;
    }

    public void setNumeroTubitos(Integer numeroTubitos) {
        this.numeroTubitos = numeroTubitos;
    }

    public Integer getNumeroAmostra() {
        return this.numeroAmostra;
    }

    public void setNumeroAmostra(Integer numeroAmostra) {
        this.numeroAmostra = numeroAmostra;
    }

    public Integer getLarvasAeg() {
        return this.larvasAeg;
    }

    public void setLarvasAeg(Integer larvasAeg) {
        this.larvasAeg = larvasAeg;
    }

    public Integer getLarvasAlb() {
        return this.larvasAlb;
    }

    public void setLarvasAlb(Integer larvasAlb) {
        this.larvasAlb = larvasAlb;
    }

    public Integer getLarvasOut() {
        return this.larvasOut;
    }

    public void setLarvasOut(Integer larvasOut) {
        this.larvasOut = larvasOut;
    }

    public boolean isExaminadoLaboratorio() {
        return this.examinadoLaboratorio;
    }

    public void setExaminadoLaboratorio(boolean examinadoLaboratorio) {
        this.examinadoLaboratorio = examinadoLaboratorio;
    }

    public Integer getDepositosInspecionados() {
        return this.depositosInspecionados;
    }

    public void setDepositosInspecionados(Integer depositosInspecionados) {
        this.depositosInspecionados = depositosInspecionados;
    }

    public boolean isUltimaVisitaBoletim() {
        return this.ultimaVisitaBoletim;
    }

    public void setUltimaVisitaBoletim(boolean ultimaVisitaBoletim) {
        this.ultimaVisitaBoletim = ultimaVisitaBoletim;
    }

    public Time getHora() {
        return this.hora;
    }
    
    public void setQuadraConcluida(boolean quadraConcluida){
    	this.quadraConcluida = quadraConcluida;
    }
    
    public boolean isQuadraConcluida(){
    	return this.quadraConcluida;
    }

    public void setHora(Time hora) {
        this.hora = hora;
    }

    /**
     * @return the boletimpesquisa
     */
    public Integer getIdBoletimpesquisa() {
        return idBoletimpesquisa;
    }

    /**
     * @param boletimpesquisa the boletimpesquisa to set
     */
    public void setIdBoletimpesquisa(Integer boletimpesquisa) {
        this.idBoletimpesquisa = boletimpesquisa;
    }

    @Override
    public boolean equals(Object obj) {

        Visitapesquisa outro = (Visitapesquisa) obj;
        
        if ((this.getIdVisitaPesquisa() != null && outro.getIdVisitaPesquisa() != null) 
                && this.getIdVisitaPesquisa().equals(outro.getIdVisitaPesquisa())) {
            return true;
        }

        if (this.getHora().equals(outro.getHora())
                && this.getIdQuadra().equals(outro.getIdQuadra())
                && this.getIdImovel().equals(outro.getIdImovel())) {
            return true;
        }

        return false;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + (this.idVisitaPesquisa != null ? this.idVisitaPesquisa : 0);
        hash = 47 * hash + (this.idQuadra != null ? this.getIdQuadra() : 0);
        hash = 47 * hash + (this.idImovel != null ? this.getIdImovel() : 0);
        return hash;
    }
}
