package ufop.smd.modelo;

import java.sql.Time;

import ufop.smd.controle.utils.Horas;
import android.content.ContentValues;
import android.database.Cursor;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

/**
 * Visitatratamento generated by hbm2java
 */
public class Visitatratamento implements Parcelable {

	private Integer idVisitaTratamento;
	private Integer idBoletimtratamento;
	private Integer idQuadra;
	private Integer idLogradouro;
	private Integer idImovel;
	private String tipoUnidade;
	private Integer inseticidaLarvicida;
	private Integer inseticidaAdulticida;
	private Boolean pendenciaRec;
	private Boolean pendenciaFech;
	private Boolean pendenciaResg;
	private Integer depositosTratados;
	private Boolean ultimaVisitaBoletim;
	private boolean quadraConcluida;
	private Time hora;

	public Visitatratamento() {
	}

	public Visitatratamento(Integer idBoletim, Integer quadra, Integer logradouro, Integer imovel, String tipoUnidade, 
			int depositosTratados, Boolean ultimaVisitaBoletim, boolean quadraConcluida, Time hora) {
		this.idBoletimtratamento = idBoletim;
		this.idQuadra = quadra;
		this.idLogradouro = logradouro;
		this.idImovel = imovel;
		this.tipoUnidade = tipoUnidade;
		this.depositosTratados = depositosTratados;
		this.ultimaVisitaBoletim = ultimaVisitaBoletim;
		this.quadraConcluida = quadraConcluida;
		this.hora = hora;
	}
	public Visitatratamento(Integer idBoletim, Integer quadra, Integer logradouro, Integer imovel, String tipoUnidade, Integer inseticidaLarvicida, 
			Integer inseticidaAdulticida, Boolean pendenciaRec, Boolean pendenciaFech, Boolean pendenciaResg, int depositosTratados, 
			Boolean ultimaVisitaBoletim, boolean quadraConcluida, Time hora) {
		this.idBoletimtratamento = idBoletim;
		this.idQuadra = quadra;
		this.idLogradouro = logradouro;
		this.idImovel = imovel;
		this.tipoUnidade = tipoUnidade;
		this.inseticidaLarvicida = inseticidaLarvicida;
		this.inseticidaAdulticida = inseticidaAdulticida;
		this.pendenciaRec = pendenciaRec;
		this.pendenciaFech = pendenciaFech;
		this.pendenciaResg = pendenciaResg;
		this.depositosTratados = depositosTratados;
		this.ultimaVisitaBoletim = ultimaVisitaBoletim;
		this.quadraConcluida = quadraConcluida;
		this.hora = hora;
	}
	public Visitatratamento(Cursor cursor){

		setIdVisitaTratamento(cursor.getInt(0));
		setIdBoletimtratamento(cursor.getInt(1));
		setIdQuadra(cursor.getInt(2));
		setIdLogradouro(cursor.getInt(3));
		setIdImovel(cursor.getInt(4));
		setTipoUnidade(cursor.getString(5));
		setInseticidaLarvicida(cursor.getInt(6));
		setInseticidaAdulticida(cursor.getInt(7));
		setPendenciaRec((cursor.getInt(8) == 1 ? true : false));
		setPendenciaFech((cursor.getInt(9) == 1 ? true : false));
		setPendenciaResg((cursor.getInt(10) == 1 ? true : false));
		setDepositosTratados(cursor.getInt(11));
		setUltimaVisitaBoletim((cursor.getInt(12) == 1 ? true : false));
		setQuadraConcluida((cursor.getInt(13) == 1 ? true : false));
		setHora(Horas.getTime(cursor.getString(14)));

	}

	public int describeContents() {
		return 0;
	}

	public void writeToParcel(Parcel dest, int flags) {

		dest.writeInt(idVisitaTratamento);
		dest.writeInt(idBoletimtratamento);
		dest.writeInt(idQuadra);
		dest.writeInt(idLogradouro);
		dest.writeInt(idImovel);
		dest.writeString(tipoUnidade);
		dest.writeInt(inseticidaLarvicida);
		dest.writeInt(inseticidaAdulticida);
		dest.writeString(pendenciaRec + "");
		dest.writeString(pendenciaFech + "");
		dest.writeString(pendenciaResg + "");
		dest.writeInt(depositosTratados);
		dest.writeString(ultimaVisitaBoletim + "");
		dest.writeString(quadraConcluida + "");
		dest.writeString(hora + "");

	}

	public static final Parcelable.Creator<Visitatratamento> CREATOR = new Parcelable.Creator<Visitatratamento>() {


		public Visitatratamento createFromParcel(Parcel parcel) {

			Visitatratamento vis = new Visitatratamento();

			vis.setIdVisitaTratamento(parcel.readInt());
			vis.setIdBoletimtratamento(parcel.readInt());
			vis.setIdQuadra(parcel.readInt());
			vis.setIdLogradouro(parcel.readInt());
			vis.setIdImovel(parcel.readInt());
			vis.setTipoUnidade(parcel.readString());
			vis.setInseticidaLarvicida(parcel.readInt());
			vis.setInseticidaAdulticida(parcel.readInt());
			vis.setPendenciaRec(new Boolean(parcel.readString()));
			vis.setPendenciaFech(new Boolean(parcel.readString()));
			vis.setPendenciaResg(new Boolean(parcel.readString()));
			vis.setDepositosTratados(parcel.readInt());
			vis.setUltimaVisitaBoletim(new Boolean(parcel.readString()));
			vis.setQuadraConcluida(new Boolean(parcel.readString()));
			vis.setHora(Horas.getTime(parcel.readString()));

			return vis;
		}


		public Visitatratamento[] newArray(int numElementos) {
			return new Visitatratamento[numElementos];
		}
	};

	public ContentValues getContentValues(){

		ContentValues values = new ContentValues();

		values.put("idVisitaTratamento", this.getIdVisitaTratamento() != null ? this.getIdVisitaTratamento() : null);
		values.put("idBoletimTratamento", this.getIdBoletimtratamento() != null ? this.getIdBoletimtratamento() : null);
		values.put("idQuadra", this.getIdQuadra() != null ? this.getIdQuadra() : null);
		values.put("idLogradouro", this.getIdLogradouro() != null ? this.getIdLogradouro() : null);
		values.put("idImovel", this.getIdImovel() != null ? this.getIdImovel() : null);
		values.put("tipoUnidade", this.getTipoUnidade() != null ? this.getTipoUnidade() : null);
		values.put("inseticidaLarvicida", this.getInseticidaLarvicida() != null ? this.getInseticidaLarvicida() : null);
		values.put("inseticidaAdulticida", this.getInseticidaAdulticida() != null ? this.getInseticidaAdulticida() : null);
		values.put("pendenciaRec", this.getPendenciaRec() != null ? this.getPendenciaRec() : null);
		values.put("pendenciaFech", this.getPendenciaFech() != null ? this.getPendenciaFech() : null);
		values.put("pendenciaResg", this.getPendenciaResg() != null ? this.getPendenciaResg() : null);
		values.put("depositosTratados", this.getDepositosTratados());
		values.put("ultimaVisitaBoletim", this.isUltimaVisitaBoletim());
		values.put("quadraConcluida", this.isQuadraConcluida());
		values.put("hora", this.getHora() != null ? this.getHora().toString() : null);

		Log.d("smd", values.toString());

		return values;
	}

	public Integer getIdVisitaTratamento() {
		return this.idVisitaTratamento;
	}

	public void setIdVisitaTratamento(Integer idVisitaTratamento) {
		this.idVisitaTratamento = idVisitaTratamento;
	}

	public Integer getIdBoletimtratamento(){
		return this.idBoletimtratamento;
	}

	public void setIdBoletimtratamento(Integer boletimtratamento){
		this.idBoletimtratamento = boletimtratamento;
	}

	public Integer getIdQuadra() {
		return this.idQuadra;
	}

	public void setIdQuadra(Integer quadra) {
		this.idQuadra = quadra;
	}

	public Integer getIdLogradouro() {
		return this.idLogradouro;
	}

	public void setIdLogradouro(Integer logradouro) {
		this.idLogradouro = logradouro;
	}

	public Integer getIdImovel() {
		return this.idImovel;
	}

	public void setIdImovel(Integer imovel) {
		this.idImovel = imovel;
	}

	public String getTipoUnidade() {
		return this.tipoUnidade;
	}

	public void setTipoUnidade(String tipoUnidade) {
		this.tipoUnidade = tipoUnidade;
	}

	public Integer getInseticidaLarvicida() {
		return this.inseticidaLarvicida;
	}

	public void setInseticidaLarvicida(Integer inseticidaLarvicida) {
		this.inseticidaLarvicida = inseticidaLarvicida;
	}

	public Integer getInseticidaAdulticida() {
		return this.inseticidaAdulticida;
	}

	public void setInseticidaAdulticida(Integer inseticidaAdulticida) {
		this.inseticidaAdulticida = inseticidaAdulticida;
	}

	public Boolean getPendenciaRec() {
		return this.pendenciaRec;
	}

	public void setPendenciaRec(Boolean pendenciaRec) {
		this.pendenciaRec = pendenciaRec;
	}

	public Boolean getPendenciaFech() {
		return this.pendenciaFech;
	}

	public void setPendenciaFech(Boolean pendenciaFech) {
		this.pendenciaFech = pendenciaFech;
	}

	public Boolean getPendenciaResg() {
		return this.pendenciaResg;
	}

	public void setPendenciaResg(Boolean pendenciaResg) {
		this.pendenciaResg = pendenciaResg;
	}

	public Integer getDepositosTratados() {
		return this.depositosTratados;
	}

	public void setDepositosTratados(Integer depositosTratados) {
		this.depositosTratados = depositosTratados;
	}

	public Boolean isUltimaVisitaBoletim() {
		return this.ultimaVisitaBoletim;
	}

	public void setUltimaVisitaBoletim(Boolean utimaVisitaQuadra) {
		this.ultimaVisitaBoletim = utimaVisitaQuadra;
	}
	
	public boolean isQuadraConcluida() {
		return quadraConcluida;
	}

	public void setQuadraConcluida(boolean quadraConcluida) {
		this.quadraConcluida = quadraConcluida;
	}

	public Time getHora() {
		return this.hora;
	}

	public void setHora(Time hora) {
		this.hora = hora;
	}

	@Override
	public boolean equals(Object obj){

		Visitatratamento outro = (Visitatratamento) obj;
		if((this.getIdVisitaTratamento() != null && outro.getIdVisitaTratamento() != null) 
				&& this.getIdVisitaTratamento().equals(outro.getIdVisitaTratamento())){
			return true;
		}

		if(this.getHora().equals(outro.getHora())
				&& this.getIdQuadra().equals(outro.getIdQuadra())
				&& this.getIdImovel().equals(outro.getIdImovel())){
			return true;
		}

		return false;
	}

	@Override
	public int hashCode() {
		int hash = 5;
		hash = 47 * hash + (this.idVisitaTratamento != null ? this.idVisitaTratamento : 0);
		hash = 47 * hash + (this.idQuadra != null ? this.getIdQuadra() : 0);
		hash = 47 * hash + (this.idImovel != null ? this.getIdImovel() : 0);
		return hash;
	}


}
